# example netlify.toml
[build]
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugin.inputs]
    enable = false

[[redirects]]
  from = "/class"
  to = "https://microsoft.com"
  status = 307
  force = true

[[redirects]]
  from = "/kickoff"
  to = "https://apple.com"
  status = 307
  force = true